//
//  SettingsPresenter.swift
//  productName
//
//  Created by Galoyannnn on 01.06.21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SettingsPresentationLogic {
    func present(response: Settings.Main.Response)
    func present(response: Settings.Update.Response)
    func present(response: Settings.Alert.Response)
}

class SettingsPresenter: SettingsPresentationLogic {
    
    weak var viewController: SettingsDisplayLogic?
    
    // MARK: Present
    
    func present(response: Settings.Main.Response) {
        let cellUIProvider = SettingsCellUIProvider()
        let cellStyleProvider = SettingsCellStyleProvider()
        let viewModel = Settings.Main.ViewModel(cellUIProvider: cellUIProvider, cellStyleProvider: cellStyleProvider, items:  response.items)
        viewController?.display(viewModel: viewModel)
    }
    
    func present(response: Settings.Update.Response) {
        let viewModel = Settings.Update.ViewModel(items: response.items)
        viewController?.display(viewModel: viewModel)
    }
    
    func present(response: Settings.Alert.Response) {
        let viewModel = Settings.Alert.ViewModel(alertContent: response.content)
        viewController?.display(viewModel: viewModel)
    }
}

struct SettingsCellStyleProvider: SwitcherTableViewCellStyleProvider {
    
}

struct SettingsCellUIProvider: SwitchTableViewCellUIProvider {
    
}
