//
//  SettingsRouter.swift
//  productName
//
//  Created by Galoyannnn on 01.06.21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SettingsRoutingLogic {
    func routeToAlert()
}

protocol SettingsDataPassing {
    var dataStore: SettingsDataStore? { get }
}

class SettingsRouter: NSObject, SettingsRoutingLogic, SettingsDataPassing {
    weak var viewController: SettingsViewController?
    var dataStore: SettingsDataStore?
    
    // MARK: Routing
    
    func routeToAlert() {

    }
    
    // MARK: Navigation
    
    func navigateToAlert(source: SettingsViewController, destination: UIAlertController) {

        source.present(destination, animated: true)
    }
    
    // MARK: Passing data
    
//    func passDataToAlert(source: SettingsDataStore, destination: inout SomewhereDataStore) {
//        
//    }
}
