//
//  SettingsModels.swift
//  productName
//
//  Created by Galoyannnn on 01.06.21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Settings {
    // MARK: Use cases
    
    enum Main {
        struct Request {
            
        }
        
        struct Response {
            var items: [Cell]
        }
        
        struct ViewModel {
            var cellUIProvider: SettingsCellUIProvider
            var cellStyleProvider: SettingsCellStyleProvider
            var items: [Cell]
        }
    }
    
    enum Update {
        struct Request {
            
        }
        
        struct Response {
            var items: [Cell]
        }
        
        struct ViewModel {
            var items: [Cell]
        }
    }
    
    enum Alert {
        struct Request {
            
        }
        
        struct Response {
            let content:  (String, String, String)
        }
        
        struct ViewModel {
            let alertContent:  (String, String, String)
        }
    }
    
    struct Cell {
        var identifier: Int
        var title: String
        var enabled: Bool
        var cellAction: ((_ value: Bool) -> Void)
    }
}
